---
title: "Economy_AWA_ausbezahlt"
subtitle: '-'
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
    theme: lumen
    highlight: tango
---


```{r Vorbereitungen, echo=T,echo = F,collapse=TRUE, warning=FALSE,  message=FALSE}
rm(list=ls())
options(stringsAsFactors = F)

### Packages 
library(readxl)
library(dplyr)
library(ggplot2)
library(scales)
library(plotly)
library(statR)

# db_connect.r
source("~/covid19monitoring_server/db_connect.r") #Zugangsdaten

options(digits=4)
```

```{sql connection=statop, output.var = "statent"}
--kein öffentlicher Datensatz
select municipality_cd, noga082, statyear, sum(emptot) as emptot, sum(empfte) as empfte, count(*) as betriebe 
from datashop.STATENT_AST_MV where statyear = 2017 and canton_cd = 'ZH'
group by municipality_cd, statyear, noga082, emptot, empfte

```

```{r Ausbezahlt: Daten einlesen und allgemeine Aufbereitungen,echo = T}
#Statent vorbereiten
names(statent) <- tolower(names(statent))
statent$noga082 <- as.numeric(statent$noga082)

sheets <- excel_sheets('KAE Ausz KonPe KTZH.xlsx')
datalist <- list()
statentlist <- list()
datalist_plot <-list()

counter <- 0

for(sh in sheets){
counter <- counter + 1
krzarbeit_bezahlt <- read_xlsx('KAE Ausz KonPe KTZH.xlsx',sheet =sh,skip = 1, na = c("NA",""))
month_start <-  names(krzarbeit_bezahlt)[2]
month <- gsub('[[:digit:]]','',month_start)
month <- gsub(' ...','',month)

year <- as.numeric(sub("\\D*(\\d{4}).*", "\\1", month_start))

krzarb_bezahlt <- krzarbeit_bezahlt %>%
  mutate(month = names(.)[2]) %>%
  mutate(month = gsub('[[:digit:]]','',month))%>%
  mutate(month = gsub(' ...','',month))%>%
  mutate(year = year)%>%
  select(colnames(.)[c(grep('[a-z]',colnames(.)))])%>%
  rename_all(funs(c('branche','anz_ausbezahlt_betrieb','anz_ausbezahlt_arbeitn','month','year')))%>%
  
  filter(!is.na(anz_ausbezahlt_betrieb) | !is.na(anz_ausbezahlt_arbeitn))%>%
  
  mutate(branche_string = sub(".*: ", "", branche))%>%
  mutate(noga = sub(":.*", "", branche)) %>%
  mutate(noga_codes = tolower(noga),
         noga_codes =  gsub('[a-z] ','',noga_codes),
         noga_codes = gsub('-',':',noga_codes, fixed=T),
         noga_codes = gsub('+',',',noga_codes, fixed=T))%>%
  mutate(noga_absch = noga,
         noga_absch =  gsub('[0-9]','',noga_absch),
         noga_absch = gsub(':','',noga_absch, fixed=T),
         noga_absch = gsub(' ','',noga_absch, fixed=T),
         noga_absch = gsub('-','',noga_absch, fixed=T),
         noga_absch = gsub('+','',noga_absch, fixed=T))%>%
  filter(branche!='Total')


#Anzahl Betriebe und Beschäftigte aus Statent
statent$nogagrp <- NA
for(i in unique(krzarb_bezahlt$noga_codes)){
  
  statent$nogagrp_temp <- NA
  statement <- paste0('c(',i,')')
  
  if(grepl("[A-Za-z]", i)!=T){
    statent$nogagrp_temp[statent$noga082 %in% eval(parse(text=statement))] <- i
    print(table(statent$noga082[statent$noga082 %in% eval(parse(text=statement))]))
    
    statent$nogagrp <- ifelse(is.na(statent$nogagrp),
                          statent$nogagrp_temp,
                          statent$nogagrp)
  }else{
  }
}

#Die beschäftigten Zahlen aus Statent rauslesen
statent2 <- statent %>%
  mutate(nogagrp = ifelse(is.na(nogagrp),'rest', nogagrp))%>%
  group_by(nogagrp)%>%
  summarise(betriebe = sum(betriebe),
            angestellte = sum(emptot))%>%
  rename(noga_codes=nogagrp)%>%
  mutate(monat = print(month),
         jahr = print(year))

# Mit Statent verbinden
krzarb_bezahlt2 <- krzarb_bezahlt%>%
  left_join(statent2, by='noga_codes')%>%
  select(-monat,-jahr)%>%
  
  add_row(branche = 'Total', 
          anz_ausbezahlt_betrieb = sum(.$anz_ausbezahlt_betrieb), 
          anz_ausbezahlt_arbeitn = sum(.$anz_ausbezahlt_arbeitn),
          month = unique(month),
          year = unique(year),
          branche_string = 'Alle Branchen',
          angestellte = sum(.$angestellte),
          betriebe = sum(.$betriebe),
          noga = 'Alle Branchen')%>%
  
  mutate(share_ausbezahlt_besch  = round(anz_ausbezahlt_arbeitn/angestellte,2),
         share_ausbezahlt_betriebe = round(anz_ausbezahlt_betrieb/betriebe,2)) %>%
  #tidyr::pivot_longer(-date,names_to='variable_short',values_to='value')%>%
  

  tidyr::gather('variable_short','value',-month,-year,-branche,-branche_string,-noga,-noga_codes,-noga_absch, -angestellte,-betriebe)%>%
  
  mutate(variable_long = case_when(
    variable_short=='anz_ausbezahlt_betrieb' ~ 'Kurzarbeit ausbezahlt Anzahl Betriebe',
    variable_short=='anz_ausbezahlt_arbeitn' ~ 'Kurzarbeit ausbezahlt Anzahl Beschäftigte',
    variable_short=='share_ausbezahlt_besch' ~ 'Kurzarbeit ausbezahlt Anteil Beschäftigte',
    variable_short=='share_ausbezahlt_betriebe' ~ 'Kurzarbeit ausbezahlt Anteil Betriebe',
     TRUE ~ 'NA'),

    variable_short = ifelse(variable_short == 'anz_ausbezahlt_arbeitn', 'anz_ausbezahlt_besch', variable_short),
         description = 'https://github.com/statistikZH/covid19monitoring_economy_AWA',
         location = 'ZH',
         topic = 'Wirtschaft',
         unit = ifelse(grepl('share_',variable_short),'Anteil','Anzahl'),
         source = 'Amt für Wirtschaft und Arbeit Kanton Zürich',
         update = 'monatlich',
         public = 'ja') %>%
    select(topic,year,month,value,variable_short,variable_long,location,branche_string,noga,public,description,unit,source,update)

datalist[[counter]] <- krzarb_bezahlt2[krzarb_bezahlt2$noga!='Rest' & !krzarb_bezahlt2$variable_short %in% c('share_ausbezahlt_besch','share_ausbezahlt_betriebe') ,]
statentlist[[counter]] <- statent2

datalist_plot[[counter]] <- krzarb_bezahlt

}

Economy_AWA_ausbezahlt <- do.call(rbind, datalist)

#Welche NOGA_Dodes sind stabil, bzw. werden in jedem Monat für die Statentauswertung benutzt
Statent_Codes <- do.call(rbind, statentlist)
Statent_Codes_stabil <- data.frame(table(Statent_Codes$noga_codes))
Statent_Codes <- merge(Statent_Codes,Statent_Codes_stabil, by.x='noga_codes',by.y='Var1')
Statent_Codes$valid <- ifelse(Statent_Codes$Freq==max(Statent_Codes$Freq),1,0)
Statent_Codes <- Statent_Codes%>%
  rename(year=jahr,month=monat)

#Dies ist der Ausgangsdatensatz, um Zweireihen zu produzieren
Economy_AWA_ausbezahlt_plotstart <- do.call(rbind, datalist_plot) 

#Datensatz speichern
write.csv(Economy_AWA_ausbezahlt,'Economy_AWA_kurzarbeit_ausbezahlt.csv',row.names=F, fileEncoding = "UTF-8")
#View(krzarbeit)


```

```{sql noga-codes abschnitte, connection=statop, output.var = "noga_abschnitte" }
select ABSCHNITTE as noga_absch, NOGA2008_DESC as noga_string from OEC.NOGA2008_CODES_MV where STUFE = 1
```

```{r Plots}
names(noga_abschnitte) <- tolower(names(noga_abschnitte))


pldf <-  Economy_AWA_ausbezahlt_plotstart%>%
  left_join(Statent_Codes, by=c('noga_codes','month','year'))%>%
  left_join(noga_abschnitte, by='noga_absch')%>%
 
  mutate(noga_absch = ifelse(noga_codes %in% Statent_Codes$noga_codes[Statent_Codes$valid==1],noga_absch,'Rest'))%>%
  mutate(noga_string = ifelse(noga_absch == 'Rest','Andere',noga_string))%>%
  mutate(noga_absch = ifelse(noga_absch == 'Rest','X',noga_absch))%>%
  group_by(noga_absch, month, year,noga_string)%>%
  
  summarise(anz_ausbezahlt_betrieb = sum(anz_ausbezahlt_betrieb),
            anz_ausbezahlt_arbeitn = sum(anz_ausbezahlt_arbeitn),
            anz_betriebe = sum(betriebe),
            anz_angestellte = sum(angestellte))%>%
  
  mutate(share_ausbezahlt_arbeitn = anz_ausbezahlt_arbeitn/anz_angestellte,
         share__ausbezahlt_betriebe = anz_ausbezahlt_betrieb/anz_betriebe)%>%
  mutate(noga_string = case_when(
    noga_string == 'Land- und Forstwirtschaft, Fischerei' ~ 'Land- und Forstwirtschaft',
    noga_string == 'Verarbeitendes Gewerbe/Herstellung von Waren' ~  'Verarbeitendes und herstellendes Gewerbe\n(ohne Fahrzeug- und Automobilproduktion)',
    noga_string == 'Gastgewerbe/Beherbergung und Gastronomie' ~ 'Beherbergung und Gastronomie',
    noga_string == 'Handel; Instandhaltung und Reparatur von Motorfahrzeuge' ~ 'Handel allgemein und Motorfahrzeuggaragen',
    noga_string == 'Erbringung von Finanz- und Versicherungsdienstleistungen' ~ 'Finanz- und Versicherungsdienstleistungen',
    noga_string == 'Erbringung von freiberuflichen, wissenschaftlichen und technischen Dienstleistungen' ~ 'Freiberufliche, wissenschaft.\nund techn. Dienstleistungen',
    noga_string == 'Erbringung von sonstigen wirtschaftlichen Dienstleistungen' ~ 'Sonstige wirtschaftliche Dienstleistungen',
    noga_string == 'Erbringung von sonstigen Dienstleistungen' ~ 'Sonstige Dienstleistungen',
    TRUE ~ as.character(noga_string)))%>%
  ungroup()%>%
  mutate(noga_string = forcats::fct_reorder(noga_string, desc(noga_absch)))%>%

  

   tidyr::gather('variable_short','value',-month,-year,-noga_absch, -noga_string, -anz_angestellte,-anz_betriebe, -share__ausbezahlt_betriebe,-share_ausbezahlt_arbeitn) %>%
  
  mutate(label = paste0(round(value*100,1),' %'))%>%
  mutate(variable_short = ifelse(variable_short=='anz_ausbezahlt_arbeitn','Beschäftigte','Betriebe'),
         month = factor(month, levels = c('April',
                                          'März')))
  
ggplot(pldf,aes(noga_string,value,fill=month))+
  geom_col(position = 'dodge')+
  geom_text(aes(label = label, y = (value+0.01)),position = position_dodge(width = 1),size=8, hjust=0)+
  scale_y_continuous(labels = scales::percent, limits=c(0,1))+
  coord_flip()+
  
  labs(y = NULL, 
       x = NULL, 
       title = "Kurzarbeitsentschädigung im Kanton Zürich nach Branchen\n",
       subtitle = NULL,
       caption = paste0('\nDaten: Amt für Wirtschaft und Arbeit Kanton Zürich / STATENT 2017'))+
  
  theme_stat()+
  facet_wrap(~variable_short)+
  scale_fill_manual(values=zhpal$zh[c(1,3)], breaks= c('März','April'))+
    theme(legend.position = "top",
        legend.title=element_blank()) +
  theme(
    axis.line = element_line(color="black", size = 1),
    axis.text = element_text(color="black", size = 25,face = "bold"),
    axis.title = element_text(color="black", size = 25,face = "bold"),
    axis.ticks.y = element_blank(),
  
    plot.title = element_text(color="black", size = 40,face = "bold",hjust = +0.5),
    plot.caption= element_text(color="black", size=20),
    
    legend.title=element_blank(),
    legend.text= element_text(color="black", size=15),
    legend.key.size = unit(2,"line"),
    
    strip.text.x = element_text(color="black", size = 30,face = "bold"))

ggsave('plots/Economy_AWA_ausbezahlt_branchen_short_two_months.png',width = 22.86, height =14.128, units = c("cm"),dpi=300,scale=3)

```

```{r tweet plot}

pldf2 <- pldf %>%
  filter(month=='April')%>%
  filter(variable_short=='Beschäftigte')%>%
  mutate(noga_string2 = forcats::fct_reorder(noga_string, value))%>%
  mutate(noga_string2 =   forcats::fct_relevel(noga_string2, "Andere", after = 0))


ggplot(pldf2,aes(noga_string2,round(value/1000,1)))+
  geom_col(position = 'dodge', fill= zhpal$zh[1])+
  #geom_text(aes(label = label, y = (value+0.01)),position = position_dodge(width = 1),size=8, hjust=0)+
  #geom_text(aes(label = round(value/1000,1), y = (round(value/1000,1)+1)),position = position_dodge(width = 1),size=8, hjust=0)+
  #scale_y_continuous(labels = scales::percent, limits=c(0,1))+
  coord_flip()+
  
  labs(y = 'Beschäftigte mit Kurzarbeit in Tausend', 
       x = NULL, 
       title = "Kurzarbeitsentschädigung im Kanton Zürich nach Branchen: April 2020",
       subtitle = 'Branchen entsprechen NOGA-Abschnitten mit angepasster Bezeichnung. Abschnitt Verarbeitendes und Herstellendes Gewerbe ohne Automobilsektoren.\n',
       caption = paste0('\nDaten: Amt für Wirtschaft und Arbeit Kanton Zürich\nAufbereitung: Statistisches Amt Kanton Zürich\n'))+
  theme_stat() + 
  theme(legend.position = "none")+
  
  #scale_fill_manual(values=zhpal$zh[c(1,3)], breaks= c('März','April'))+
  
  #theme(legend.position = "top",
  #      legend.title=element_blank()) +
  theme(
    axis.line = element_line(color="black", size = 1),
    axis.text = element_text(color="black", size = 25,face = "bold"),
    axis.title = element_text(color="black", size = 25,face = "bold"),
    axis.ticks.y = element_blank(),
  
    plot.title = element_text(color="black", size = 40,face = "bold"),
    plot.subtitle = element_text(color="black", size = 20),
    plot.caption= element_text(color="black", size=20),
    
    legend.title=element_blank(),
    legend.text= element_text(color="black", size=15),
    legend.key.size = unit(2,"line"),
    
    strip.text.x = element_text(color="black", size = 30,face = "bold"))

ggsave('plots/Economy_AWA_krzarb_branchen_absolut_april.png',width = 22.86, height =14.128, units = c("cm"),dpi=300,scale=3)
```


