---
title: "Economy_AWA"
subtitle: '-'
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
    theme: lumen
    highlight: tango
---


```{r Vorbereitungen, echo=T,echo = F,collapse=TRUE, warning=FALSE,  message=FALSE}
rm(list=ls())
options(stringsAsFactors = F)

### Packages 
library(readxl)
library(dplyr)
library(ggplot2)
library(scales)
library(plotly)
```

```{r Daten einlesen und allgemeine Aufbereitungen,echo = T}
krzarbeit <- read_xlsx('KAE Voranm KTZH.xlsx',sheet ='KArb VA U AN täglich Kanton ...') %>%
  slice(-c(1,2)) %>%
  rename_all(funs(c('date','kum_kurzarbeitzh_bew_betrieb','kum_kurzarbeitzh_bew_arbeitn')))%>%
  mutate(date = as.POSIXct(date, format = '%Y%m%d'))%>%
  #tidyr::pivot_longer(-date,names_to='variable_short',values_to='value')%>%
  tidyr::gather('variable_short','value',-date)%>%
  mutate(variable_long = ifelse(variable_short=='kum_kurzarbeitzh_bew_betrieb','Kumulierte bewilligte Voranmeldungen Kurzarbeit Betriebe','Kumulierte bewilligte Voranmeldungen Kurzarbeit voraussichtlich betroffene Arbeitn.'),
         description = 'https://github.com/statistikZH/covid19monitoring_economy_AWA',
         location = 'ZH',
         topic = 'Wirtschaft',
         unit = 'Anzahl',
         source = 'Amt für Wirtschaft und Arbeit Kanton Zürich',
         update = 'täglich',
         public = 'ja') %>%
    select(date,value,topic,variable_short,variable_long,location,unit,source,update,public,description)

#Datensatz speichern
write.csv(krzarbeit,'Economy_AWA.csv',row.names=F, fileEncoding = "UTF-8")
View(krzarbeit)


#Bewilligte Gesuche: 20200301 - 20200405
krzarbeit_bis5April <- read_xlsx('KAE Voranm KTZH.xlsx',sheet ='KArb VA U AN täglich Kanton ...') %>%
  slice(2) %>%
  rename_all(funs(c('date','kum_kurzarbeitzh_bew_betrieb_bis_5april','kum_kurzarbeitzh_bew_arbeitn_bis_5april')))%>%
  mutate(date = as.POSIXct(substring(date,10,19), format = '%Y%m%d'))%>%
  #tidyr::pivot_longer(-date,names_to='variable_short',values_to='value')%>%
  tidyr::gather('variable_short','value',-date)%>%
  mutate(variable_long = ifelse(variable_short=='kum_kurzarbeitzh_bew_betrieb_bis_5april','Kumuliertes Total Bewilligte Voranmeldungen Kurzarbeit Betriebe bis 5 April 2020','Kumuliertes Total Bewilligte Voranmeldungen Kurzarbeit voraussichtlich betroffene Arbeitn. bis 5. April 2020'),
         description = 'https://github.com/statistikZH/covid19monitoring_economy_AWA',
         location = 'ZH',
         topic = 'Wirtschaft',
         unit = 'Anzahl',
         source = 'Amt für Wirtschaft und Arbeit Kanton Zürich',
         update = 'täglich',
         public = 'ja') %>%
    select(date,value,topic,variable_short,variable_long,location,unit,source,update,public,description)

write.csv(krzarbeit_bis5April,'Economy_AWA_total_bis_5april.csv',row.names=F, fileEncoding = "UTF-8")
```